Estates/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from MyPlace import settings
from django.conf.urls.static import static
from . import views

app_name = 'Estates'

urlpatterns = [
    url(r'^$', views.estate_list, name='list'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyPlace/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from Estates import views as estate_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', estate_views.estate_list, name="home"),
    url(r'^accounts/', include('Owner.urls')),
    url(r'^estates/', include('Estates.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Owner/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from MyPlace import settings
from django.conf.urls.static import static
from . import views

app_name = 'owner'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Estates/models.py
from datetime import datetime
from django.db import models
from Owner.models import Owner
from django_resized import ResizedImageField

class Estate(models.Model):
    Types_of_building = [(1, ('Mieszkanie')),
                         (2, ('Apartament')),
                         (3, ('Szeregówka')),
                         (4, ('Dom')),
                         (5, ('Loft')),
                         (6, ('Inne'))]

    Materials_of_building = [(1, ('CEGŁA')),
                             (2, ('DREWNO')),
                             (3, ('WIELKA PŁYTA')),
                             (4, ('PUSTAK')),
                             (5, ('BETON')),
                             (6, ('ŻELBET')),
                             (6, ('INNE'))
                             ]

    owner = models.ForeignKey(Owner, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=100)
    surface = models.CharField(max_length=8)
    type_of_building = models.IntegerField(choices=Types_of_building, default='INNE')
    material_of_building = models.IntegerField(choices=Materials_of_building, default='INNE')
    year_of_building = models.IntegerField(default='2020')
    number_of_rooms = models.IntegerField()
    number_of_bathrooms = models.IntegerField()
    number_of_floors = models.IntegerField()
    max_floor = models.IntegerField()
    free_from = models.DateTimeField(blank=True)
    garage = models.BooleanField(default=False)
    parking_slot = models.BooleanField(default=False)
    price = models.CharField(max_length=6)
    city = models.CharField(max_length=15)
    street = models.CharField(max_length=30)
    description = models.TextField(blank=True)
    main_photo = ResizedImageField(upload_to='media/%Y/%m/%d', size = [480,240])
    photo_1 = ResizedImageField(upload_to='media/%Y/%m/%d', size = [480,240], blank=True)
    photo_2 = ResizedImageField(upload_to='media/%Y/%m/%d', size = [480,240], blank=True)
    photo_3 = ResizedImageField(upload_to='media/%Y/%m/%d', size = [480,240], blank=True)
    photo_4 = ResizedImageField(upload_to='media/%Y/%m/%d', size = [480,240], blank=True)
    photo_5 = ResizedImageField(upload_to='media/%Y/%m/%d', size = [480,240], blank=True)
    photo_6 = ResizedImageField(upload_to='media/%Y/%m/%d', size = [480,240], blank=True)
    published = models.DateTimeField(default=datetime.now)
    reserved = models.BooleanField(default=False)

    def __str__(self):
        return self.title

Owner/models.py
from django.db import models
from datetime import datetime


class Owner(models.Model):
    name_and_surname = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10)
    photo = models.ImageField(upload_to='media/%Y/%m/%d')
    email = models.CharField(max_length=30)
    joined = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.name_and_surname

Estates/forms.py
from django import forms
from . import models


class CreateEstateOffer(forms.ModelForm):
    class Meta:
        model = models.Estate
        fields = ['title',
                  'surface',
                  'type_of_building',
                  'material_of_building',
                  'year_of_building',
                  'number_of_rooms',
                  'number_of_bathrooms',
                  'number_of_floors',
                  'max_floor',
                  'free_from',
                  'garage',
                  'parking_slot',
                  'price',
                  'city',
                  'street',
                  'description',
                  'main_photo',
                  'photo_1',
                  'photo_2',
                  'photo_3',
                  'photo_4',
                  'photo_5',
                  'photo_6',
                  'published',
                  'reserved']

Estates/views.py
from django.shortcuts import render
from .models import Estate
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.


def estate_list(request):
    estates = Estate.objects.all().order_by('published')
    return render(request, 'estates/estate_list.html', {'estates': estates})


def estate_detail(request):
    pass


@login_required(login_url='/owner/login')
def estate_create(request):
    form = forms.CreateEstateOffer()
    return render(request, 'estates/estate_add.html', {'form': form})

Owner/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'Owner/signup.html', {'form': form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'Owner/login.html', {'form': form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('home')

Estates/templates/Estates/estate_add.html
{% extends 'home.html' %}

{% load static %}

{% block content %}
<div class="add-estate">
    <h2>Add New Estate Offer</h2>
    <form class="site-form" action="{% url 'estates:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Dodaj">
    </form>
</div>
{% endblock %}

Estates/templates/Estates/estate_list.html
{% extends 'home.html' %}

{% load static %}

{% block content %}
<div class="before-listing">
    <div class="container">
        <p class="alignleft"> Liczba ofert: <strong>{{ estates.count }}</strong></p>
        <p class="alignright"> Sortuj po: </p>
        <div style="clear: both;"></div>
    </div>
</div>
<div class="listing">
    <div class="container">
            {% for estate in estates %}
                <div class="grid-container">
                    <div class="image"><img class="estate-img" height="200px" src="{{ estate.main_photo.url }}" width="400px"/></div>
                    <div class="estate-text">
                        <div class="title">{{ estate.title }}</div>
                        <div class="subtitle">{{ estate.get_type_of_building_display }} na sprzedaż {{ estate.street }}, {{ estate.city }}</div>
                        <br><br>
                        <div class="info">
                            <p class="alignleft">{{ estate.number_of_rooms }} pokoje {{ estate.surface }} m<sup>2</sup></p>
                            <p class="alignright">{{ estate.price }} zł</p>
                            <div style="clear: both;"></div>
                        </div>
                    </div>
                </div>
            {% endfor %}
    </div>
</div>
{% endblock %}

Estates/templates/Estates/search_bar.html
{% extends home.html %}

{% block title %}{{ | search_bar }}{% endblock %}

{% block content %}

{% endblock %}

Owner/templates/Owner/login.html
<h1>Log in</h1>
<form class="site-form" action="{% url 'owner:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type = "submit" value="login">
</form>

Owner/templates/Owner/signup.html
    <h1>Signup</h1>
    <form class="site-form" action="/owner/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type = "submit" value="Signup">
    </form>

templates/footer.html
{% load static %}

 <footer class="page-footer blue-grey lighten-1">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="https://www.freepik.com/photos/travel">Travel photo created by katemangostar - www.freepik.com</a>
            </div>
          </div>
 </footer>

templates/home.html
{% load static %}
<DOCTYPE html>
<html lang="en">
<head>
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Prism CSS -->
    <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="static/mystyle.css">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body style="background-color:#cfd8dc;">

    {% include 'navbar.html' %}

    {% include 'slider.html' %}

    {% block content %} {% endblock %}

    {% include 'footer.html' %}

    <script src="{% static 'tinymce/js/prism.js' %}"></script>
</body>
</html>
</DOCTYPE>

templates/navbar.html
{% load static %}

<script>
        $(document).ready(function () {
            $('.modal').modal();
            $('.dropdown-trigger').dropdown({
                hover: true,
                constrainWidth: false,
            });
        });
</script>

<nav>
        <ul id="dropdown" class="dropdown-content blue-grey lighten-1">
            <li><a href="any.html">Wynajem</a></li>
            <li><a href="any.html">Sprzedaż</a></li>
            <li><a href="any.html">Oferty deweloperów</a></li>
        </ul>

        <div class="nav-wrapper blue-grey lighten-1">
          <a href="#" class="brand-logo"><img src="media/logo.png" height="64"></a>
          <div class="navbar-list">
            <ul class="right hide-on-down">
                <li><a href="any.html">Mieszkania</a></li>
                <li><a href="any.html">Domy</a></li>
                <li><a href="any.html">Statystyki</a></li>
                {% if user.is_authenticated %}
                <li>
                    <form class = "logout-link" action="{% url 'owner:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'estates:add' %}" class="highlight">Dodaj Ogłoszenie</a></li>
                {% else %}
                    <li><a href="{% url 'owner:login' %}">Logowanie</a></li>
                    <li><a href="{% url 'owner:signup' %}">Rejestracja</a></li>
                {% endif %}
            </ul>
          </div>
        </div>
</nav>

templates/slider.html
{% load static %}

<script>
        $(document).ready(function () {
            $('.slider').slider({
                full_width: true,
                indicators: false,
                interval: 10000
            });
        });

</script>

<div class="slider">
    <ul class="slides" style="z-index:1;">
        <li>
            <img src= "media/stockphoto_slider1.jpg" width="1343" height="400">
            <div class="caption center-align">
                <h3>Znajdź odpowiednie miejsce</h3>
                <h5 class="light grey-text text-lighten-3">i stwórz w nim swój dom!</h5>
            </div>
        </li>
        <li>
            <img src= "media/stockphoto_slider2.jpg" width="1343" height="400">
            <div class="caption left-align">
                <h3>Twoje marzenia </h3>
                <h5 class="light grey-text text-lighten-3">zaczynają się tutaj!</h5>
            </div>
        </li>
        <li>
            <img src= "media/stockphoto_slider3.jpg" width="1343" height="400">
            <div class="caption right-align">
                <h3>Twoje miejsce</h3>
                <h5 class="light grey-text text-lighten-3">bliżej niż myślisz!</h5>
            </div>
        </li>
    </ul>
</div>